# fly.toml app configuration file generated for fullstack-open-cicd-patientor on 2024-05-27T15:03:56+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstack-open-cicd-patientor'
primary_region = 'arn'

[env]
PORT = '3000'

[processes]
app = 'node patientor-backend/build/src/index.js'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
